//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartManage.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aucun utilisateur n\'est encore connecté")]
        public string UserConnected {
            get {
                return ((string)(this["UserConnected"]));
            }
            set {
                this["UserConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strFormModifieSubForm {
            get {
                return ((string)(this["strFormModifieSubForm"]));
            }
            set {
                this["strFormModifieSubForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdentifiantPersonne {
            get {
                return ((int)(this["IdentifiantPersonne"]));
            }
            set {
                this["IdentifiantPersonne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StringLogFile {
            get {
                return ((string)(this["StringLogFile"]));
            }
            set {
                this["StringLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SmartManage")]
        public string MasterDirectory {
            get {
                return ((string)(this["MasterDirectory"]));
            }
            set {
                this["MasterDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log")]
        public string DirectoryUtilLog {
            get {
                return ((string)(this["DirectoryUtilLog"]));
            }
            set {
                this["DirectoryUtilLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString")]
        public string DirectoryUtilConn {
            get {
                return ((string)(this["DirectoryUtilConn"]));
            }
            set {
                this["DirectoryUtilConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserSQLSever.txt")]
        public string FileSQLServer {
            get {
                return ((string)(this["FileSQLServer"]));
            }
            set {
                this["FileSQLServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionStringRadius")]
        public string DirectoryUtilConnRadAdmin {
            get {
                return ((string)(this["DirectoryUtilConnRadAdmin"]));
            }
            set {
                this["DirectoryUtilConnRadAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirectoryUtilConnRadStudent {
            get {
                return ((string)(this["DirectoryUtilConnRadStudent"]));
            }
            set {
                this["DirectoryUtilConnRadStudent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserRadAdmin.txt")]
        public string FileRadAdmin {
            get {
                return ((string)(this["FileRadAdmin"]));
            }
            set {
                this["FileRadAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserRadStudent.txt")]
        public string FileRadStudent {
            get {
                return ((string)(this["FileRadStudent"]));
            }
            set {
                this["FileRadStudent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogFile.txt")]
        public string LogFileName {
            get {
                return ((string)(this["LogFileName"]));
            }
            set {
                this["LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogFileRadiusAdmin.txt")]
        public string LogFileNameRadiusAdmin {
            get {
                return ((string)(this["LogFileNameRadiusAdmin"]));
            }
            set {
                this["LogFileNameRadiusAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogFileRadiusStudent.txt")]
        public string LogFileNameRadiusStudent {
            get {
                return ((string)(this["LogFileNameRadiusStudent"]));
            }
            set {
                this["LogFileNameRadiusStudent"] = value;
            }
        }
    }
}
