//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesData.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        internal static string StringCancelDeleteCaption {
            get {
                return ResourceManager.GetString("StringCancelDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune suppression effectuée.
        /// </summary>
        internal static string StringCancelDeleteMessage {
            get {
                return ResourceManager.GetString("StringCancelDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification utilisateur.
        /// </summary>
        internal static string StringEmptyNewPasswordCaption {
            get {
                return ResourceManager.GetString("StringEmptyNewPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau mot de passe ne peut être vide.
        /// </summary>
        internal static string StringEmptyNewPasswordMessage {
            get {
                return ResourceManager.GetString("StringEmptyNewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification utilisateur.
        /// </summary>
        internal static string StringEmptyOldPasswordCaption {
            get {
                return ResourceManager.GetString("StringEmptyOldPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ancien mot de passe ne peut être vide.
        /// </summary>
        internal static string StringEmptyOldPasswordMessage {
            get {
                return ResourceManager.GetString("StringEmptyOldPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification utilisateur.
        /// </summary>
        internal static string StringEmptyUserNameCaption {
            get {
                return ResourceManager.GetString("StringEmptyUserNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de l&apos;utilisateur ne peut être vide.
        /// </summary>
        internal static string StringEmptyUserNameMessage {
            get {
                return ResourceManager.GetString("StringEmptyUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Documents (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string StringExcelDocumentFilterValue1 {
            get {
                return ResourceManager.GetString("StringExcelDocumentFilterValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx|All files (*.*)|*.*.
        /// </summary>
        internal static string StringExcelDocumentFilterValue2 {
            get {
                return ResourceManager.GetString("StringExcelDocumentFilterValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivage enregistrement.
        /// </summary>
        internal static string StringFailedArchiveCaption {
            get {
                return ResourceManager.GetString("StringFailedArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec d&apos;archivage.
        /// </summary>
        internal static string StringFailedArchiveMessage {
            get {
                return ResourceManager.GetString("StringFailedArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification de l&apos;utilisateur.
        /// </summary>
        internal static string StringFailedAuthenticationUserBDCaption {
            get {
                return ResourceManager.GetString("StringFailedAuthenticationUserBDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de l&apos;authentification de l&apos;utilisateur.
        /// </summary>
        internal static string StringFailedAuthenticationUserBDMessage {
            get {
                return ResourceManager.GetString("StringFailedAuthenticationUserBDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        internal static string StringFailedDeleteCaption {
            get {
                return ResourceManager.GetString("StringFailedDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la suppression.
        /// </summary>
        internal static string StringFailedDeleteMessage {
            get {
                return ResourceManager.GetString("StringFailedDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait droits d&apos;accès.
        /// </summary>
        internal static string StringFailedDenyRightAccessCaption {
            get {
                return ResourceManager.GetString("StringFailedDenyRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du retrait des droits d&apos;accès.
        /// </summary>
        internal static string StringFailedDenyRightAccessMessage {
            get {
                return ResourceManager.GetString("StringFailedDenyRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation Excel.
        /// </summary>
        internal static string StringFailedExportExcelCaption {
            get {
                return ResourceManager.GetString("StringFailedExportExcelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;exportation vers Excel.
        /// </summary>
        internal static string StringFailedExportExcelMessage {
            get {
                return ResourceManager.GetString("StringFailedExportExcelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génération QrCode.
        /// </summary>
        internal static string StringFailedGenerateQrCodeCaption {
            get {
                return ResourceManager.GetString("StringFailedGenerateQrCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la génération du QrCode.
        /// </summary>
        internal static string StringFailedGenerateQrCodeMessage {
            get {
                return ResourceManager.GetString("StringFailedGenerateQrCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions droits d&apos;accès.
        /// </summary>
        internal static string StringFailedGrantRightAccessCaption {
            get {
                return ResourceManager.GetString("StringFailedGrantRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la validation des droits.
        /// </summary>
        internal static string StringFailedGrantRightAccessMessage {
            get {
                return ResourceManager.GetString("StringFailedGrantRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement listes déroulantes.
        /// </summary>
        internal static string StringFailedLoadComboBoxCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadComboBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de chargement des listes déroulantes.
        /// </summary>
        internal static string StringFailedLoadComboBoxMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadComboBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres de connexion à la Base de Données.
        /// </summary>
        internal static string StringFailedLoadDataBaseParamsCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadDataBaseParamsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement des paramètres de connexion à la Base de Données.
        /// </summary>
        internal static string StringFailedLoadDataBaseParamsMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadDataBaseParamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des données.
        /// </summary>
        internal static string StringFailedLoadDataCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement des données.
        /// </summary>
        internal static string StringFailedLoadDataMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement zone d&apos;affichage.
        /// </summary>
        internal static string StringFailedLoadDtgvCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadDtgvCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement de la zone d&apos;affichage.
        /// </summary>
        internal static string StringFailedLoadDtgvMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadDtgvMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours de conception.
        /// </summary>
        internal static string StringFailedLoadHelpCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection photo.
        /// </summary>
        internal static string StringFailedLoadPictureCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadPictureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de chargement de la photo.
        /// </summary>
        internal static string StringFailedLoadPictureMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadPictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement rapport.
        /// </summary>
        internal static string StringFailedLoadReportCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de chargement du rapport.
        /// </summary>
        internal static string StringFailedLoadReportMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des droits.
        /// </summary>
        internal static string StringFailedLoadRightAccessCaption {
            get {
                return ResourceManager.GetString("StringFailedLoadRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement des droits.
        /// </summary>
        internal static string StringFailedLoadRightAccessMessage {
            get {
                return ResourceManager.GetString("StringFailedLoadRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de l&apos;ouverture de la connexion à la Base de données.
        /// </summary>
        internal static string StringFailedOpenConnectionBDMessage {
            get {
                return ResourceManager.GetString("StringFailedOpenConnectionBDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualisation.
        /// </summary>
        internal static string StringFailedRefreshCaption {
            get {
                return ResourceManager.GetString("StringFailedRefreshCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualisation liste déroulante.
        /// </summary>
        internal static string StringFailedRefreshLoadComboCaption {
            get {
                return ResourceManager.GetString("StringFailedRefreshLoadComboCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec d&apos;actualisation de la liste déroulante.
        /// </summary>
        internal static string StringFailedRefreshLoadComboMessage {
            get {
                return ResourceManager.GetString("StringFailedRefreshLoadComboMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;actualisation.
        /// </summary>
        internal static string StringFailedRefreshMessage {
            get {
                return ResourceManager.GetString("StringFailedRefreshMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement paramètres de connexion.
        /// </summary>
        internal static string StringFailedSaveDataBaseParamsCaption {
            get {
                return ResourceManager.GetString("StringFailedSaveDataBaseParamsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;enregistrement des paramètres de connexion.
        /// </summary>
        internal static string StringFailedSaveDataBaseParamsMessage {
            get {
                return ResourceManager.GetString("StringFailedSaveDataBaseParamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour.
        /// </summary>
        internal static string StringFailedSaveUpdateCaption {
            get {
                return ResourceManager.GetString("StringFailedSaveUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la mise à jour.
        /// </summary>
        internal static string StringFailedSaveUpdateMessage {
            get {
                return ResourceManager.GetString("StringFailedSaveUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche élément.
        /// </summary>
        internal static string StringFailedSearchCaption {
            get {
                return ResourceManager.GetString("StringFailedSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la recherche.
        /// </summary>
        internal static string StringFailedSearchMessage {
            get {
                return ResourceManager.GetString("StringFailedSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection enegistrement.
        /// </summary>
        internal static string StringFailedSelectRecordDtgvCaption {
            get {
                return ResourceManager.GetString("StringFailedSelectRecordDtgvCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la sélection d&apos;un enregistrement.
        /// </summary>
        internal static string StringFailedSelectRecordDtgvMessage {
            get {
                return ResourceManager.GetString("StringFailedSelectRecordDtgvMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection informations utilisateur.
        /// </summary>
        internal static string StringFailedSelectUserDataCaption {
            get {
                return ResourceManager.GetString("StringFailedSelectUserDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de sélection des informations de l&apos;utilisateur.
        /// </summary>
        internal static string StringFailedSelectUserDataMessage {
            get {
                return ResourceManager.GetString("StringFailedSelectUserDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        internal static string StringFailedUpdateCaption {
            get {
                return ResourceManager.GetString("StringFailedUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la modification.
        /// </summary>
        internal static string StringFailedUpdateMessage {
            get {
                return ResourceManager.GetString("StringFailedUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification utilisateur.
        /// </summary>
        internal static string StringFailedUpdateUserCaption {
            get {
                return ResourceManager.GetString("StringFailedUpdateUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la modification.
        /// </summary>
        internal static string StringFailedUpdateUserMessage {
            get {
                return ResourceManager.GetString("StringFailedUpdateUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion à la Base de données.
        /// </summary>
        internal static string StringFailOpenConnectionBDCaption {
            get {
                return ResourceManager.GetString("StringFailOpenConnectionBDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En construction.
        /// </summary>
        internal static string StringInBuildingCaption {
            get {
                return ResourceManager.GetString("StringInBuildingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonctionnalité non encore opérationnelle.
        /// </summary>
        internal static string StringInBuildingMessage {
            get {
                return ResourceManager.GetString("StringInBuildingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur l&apos;état de l&apos;application.
        /// </summary>
        internal static string StringInfoStatusAppMessage {
            get {
                return ResourceManager.GetString("StringInfoStatusAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection d&apos;une photo.
        /// </summary>
        internal static string StringLoadPictureCaption1 {
            get {
                return ResourceManager.GetString("StringLoadPictureCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des données.
        /// </summary>
        internal static string StringNoDataLoadBindingCaption {
            get {
                return ResourceManager.GetString("StringNoDataLoadBindingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;ya rien à afficher !!!.
        /// </summary>
        internal static string StringNoDataLoadBindingMessage {
            get {
                return ResourceManager.GetString("StringNoDataLoadBindingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification utilisateur.
        /// </summary>
        internal static string StringNoMatchOldPasswordCaption {
            get {
                return ResourceManager.GetString("StringNoMatchOldPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ancien mot de passe ne correspond pas.
        /// </summary>
        internal static string StringNoMatchOldPasswordMessage {
            get {
                return ResourceManager.GetString("StringNoMatchOldPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON.
        /// </summary>
        internal static string StringNoValue {
            get {
                return ResourceManager.GetString("StringNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png|JPG File|*.jpg|TIFF File|*.tif|BitMap Image|*.bmp.
        /// </summary>
        internal static string StringPictureFilter1 {
            get {
                return ResourceManager.GetString("StringPictureFilter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Files(*.png)|*.png|JPG Files(*.jpg)|*.jpg|JPEG Files(*.jpeg)|*.jpeg|TIFF Files(*.tiff)|*.tiff.
        /// </summary>
        internal static string StringPictureFilter2 {
            get {
                return ResourceManager.GetString("StringPictureFilter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression enregistrement.
        /// </summary>
        internal static string StringPromptDeleteCaption {
            get {
                return ResourceManager.GetString("StringPromptDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cet enregistrement ?.
        /// </summary>
        internal static string StringPromptDeleteMessage {
            get {
                return ResourceManager.GetString("StringPromptDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter l&apos;application.
        /// </summary>
        internal static string StringPromptQuitAppCaption {
            get {
                return ResourceManager.GetString("StringPromptQuitAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment quitter ?.
        /// </summary>
        internal static string StringPromptQuitAppMessage {
            get {
                return ResourceManager.GetString("StringPromptQuitAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est maintenant connecté ....
        /// </summary>
        internal static string StringStatusConnectedUserMessage {
            get {
                return ResourceManager.GetString("StringStatusConnectedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnecté de la base des données ....
        /// </summary>
        internal static string StringStatusDisconnectedUserMessage {
            get {
                return ResourceManager.GetString("StringStatusDisconnectedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivage enregistrement.
        /// </summary>
        internal static string StringSuccessArchiveCaption {
            get {
                return ResourceManager.GetString("StringSuccessArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivage effectué.
        /// </summary>
        internal static string StringSuccessArchiveMessage {
            get {
                return ResourceManager.GetString("StringSuccessArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion à la base de données.
        /// </summary>
        internal static string StringSuccessConnectionBDCaption {
            get {
                return ResourceManager.GetString("StringSuccessConnectionBDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion réussie.
        /// </summary>
        internal static string StringSuccessConnectionBDMessage {
            get {
                return ResourceManager.GetString("StringSuccessConnectionBDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        internal static string StringSuccessDeleteCaption {
            get {
                return ResourceManager.GetString("StringSuccessDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression effectuée.
        /// </summary>
        internal static string StringSuccessDeleteMessage {
            get {
                return ResourceManager.GetString("StringSuccessDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait droits d&apos;accès.
        /// </summary>
        internal static string StringSuccessDenyRightAccessCaption {
            get {
                return ResourceManager.GetString("StringSuccessDenyRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droits d&apos;accès retirés avec succès.
        /// </summary>
        internal static string StringSuccessDenyRightAccessMessage {
            get {
                return ResourceManager.GetString("StringSuccessDenyRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions droits d&apos;accès.
        /// </summary>
        internal static string StringSuccessGrantRightAccessCaption {
            get {
                return ResourceManager.GetString("StringSuccessGrantRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droits d&apos;accès attribué avec succès.
        /// </summary>
        internal static string StringSuccessGrantRightAccessMessage {
            get {
                return ResourceManager.GetString("StringSuccessGrantRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement.
        /// </summary>
        internal static string StringSuccessSaveCaption {
            get {
                return ResourceManager.GetString("StringSuccessSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement paramètres de connexion.
        /// </summary>
        internal static string StringSuccessSaveDataBaseParamsCaption {
            get {
                return ResourceManager.GetString("StringSuccessSaveDataBaseParamsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement effectué.
        /// </summary>
        internal static string StringSuccessSaveDataBaseParamsMessage {
            get {
                return ResourceManager.GetString("StringSuccessSaveDataBaseParamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement effectué.
        /// </summary>
        internal static string StringSuccessSaveMessage {
            get {
                return ResourceManager.GetString("StringSuccessSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        internal static string StringSuccessUpdateCaption {
            get {
                return ResourceManager.GetString("StringSuccessUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification effectuée.
        /// </summary>
        internal static string StringSuccessUpdateMessage {
            get {
                return ResourceManager.GetString("StringSuccessUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation Excel.
        /// </summary>
        internal static string StringSusccessExportExcelCaption {
            get {
                return ResourceManager.GetString("StringSusccessExportExcelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation Excel réussie.
        /// </summary>
        internal static string StringSusccessExportExcelMessage {
            get {
                return ResourceManager.GetString("StringSusccessExportExcelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur système.
        /// </summary>
        internal static string StringSystemErrorCaption {
            get {
                return ResourceManager.GetString("StringSystemErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur système interne, veuillez notifier à l&apos;administrateur.
        /// </summary>
        internal static string StringSystemErrorMessage {
            get {
                return ResourceManager.GetString("StringSystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait droits d&apos;accès.
        /// </summary>
        internal static string StringWarningSelectDenyRightAccessCaption {
            get {
                return ResourceManager.GetString("StringWarningSelectDenyRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir une catégorie des droits d&apos;accès à retirer à l&apos;utilisateur svp !!!.
        /// </summary>
        internal static string StringWarningSelectDenyRightAccessMessage {
            get {
                return ResourceManager.GetString("StringWarningSelectDenyRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions droits d&apos;accès.
        /// </summary>
        internal static string StringWarningSelectGrantRightAccessCaption {
            get {
                return ResourceManager.GetString("StringWarningSelectGrantRightAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir une catégorie des droits à attribuer à l&apos;utilisateur svp !!!.
        /// </summary>
        internal static string StringWarningSelectGrantRightAccessMessage {
            get {
                return ResourceManager.GetString("StringWarningSelectGrantRightAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUI.
        /// </summary>
        internal static string StringYesValue {
            get {
                return ResourceManager.GetString("StringYesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0.
        /// </summary>
        internal static string StringZeroDotZeroValue {
            get {
                return ResourceManager.GetString("StringZeroDotZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun enregistrement affecté.
        /// </summary>
        internal static string StringZeroRecordAffectedMessage {
            get {
                return ResourceManager.GetString("StringZeroRecordAffectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string StringZeroValue {
            get {
                return ResourceManager.GetString("StringZeroValue", resourceCulture);
            }
        }
    }
}
